// export an array of key value pairs for car manufacturers
export const manufacturers = [
  { key: 'acura', value: 'Acura' },
  { key: 'alfa-romeo', value: 'Alfa Romeo' },
  { key: 'aston-martin', value: 'Aston Martin' },
  { key: 'audi', value: 'Audi' },
  { key: 'bentley', value: 'Bentley' },
  { key: 'bmw', value: 'BMW' },
  { key: 'buick', value: 'Buick' },
  { key: 'cadillac', value: 'Cadillac' },
  { key: 'chevrolet', value: 'Chevrolet' },
  { key: 'chrysler', value: 'Chrysler' },
  { key: 'dodge', value: 'Dodge' },
  { key: 'ferrari', value: 'Ferrari' },
  { key: 'fiat', value: 'Fiat' },
  { key: 'ford', value: 'Ford' },
  { key: 'gmc', value: 'GMC' },
  { key: 'honda', value: 'Honda' },
  { key: 'hyundai', value: 'Hyundai' },
  { key: 'infiniti', value: 'Infiniti' },
  { key: 'jaguar', value: 'Jaguar' },
  { key: 'jeep', value: 'Jeep' },
  { key: 'kia', value: 'Kia' },
  { key: 'lamborghini', value: 'Lamborghini' },
  { key: 'land-rover', value: 'Land Rover' },
  { key: 'lexus', value: 'Lexus' },
  { key: 'lincoln', value: 'Lincoln' },
  { key: 'lotus', value: 'Lotus' },
  { key: 'maserati', value: 'Maserati' },
  { key: 'mazda', value: 'Mazda' },
  { key: 'mclaren', value: 'McLaren' },
  { key: 'mercedes-benz', value: 'Mercedes-Benz' },
  { key: 'mini', value: 'Mini' },
  { key: 'mitsubishi', value: 'Mitsubishi' },
  { key: 'nissan', value: 'Nissan' },
  { key: 'porsche', value: 'Porsche' },
  { key: 'ram', value: 'Ram' },
  { key: 'rolls-royce', value: 'Rolls-Royce' },
  { key: 'subaru', value: 'Subaru' },
  { key: 'tesla', value: 'Tesla' },
  { key: 'toyota', value: 'Toyota' },
  { key: 'volkswagen', value: 'Volkswagen' },
  { key: 'volvo', value: 'Volvo' }
]
